[package]
name = "snake-game"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.81"

[dependencies.web-sys]
version = "0.3.58"
features = [
    "Document", "Window", "HtmlElement", "CssStyleDeclaration"
]
